### PR TITLE
Update frFR.lua for 2024.31.0

### PR DESCRIPTION
**Pull request by Brainc3ll**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Item fix
- [ ] Documentation
- [ ] Other

## Checklist

- [ ] I've tested what I've added
- [ ] I've updated AUTHORS.md with my name (if I want to)

## Description

Please describe your changes here. If this fixes a bug, please link to the issue, if possible.

### CODE REVIEW

**Comment by t-mart** [comment]
Thanks! I'll merge this in tomorrow morning.

**Comment by Brainc3ll** [comment]
> Thanks! I'll merge this in tomorrow morning.

You're welcome

**Comment by t-mart** [comment]
I just started the GH Action that merges this into the release branch, but...

Usually, I'd publish changes like this immediately to CurseForge too. However, I want to experiment with waiting on this one: Because this isn't a critical fix, I don't want to burden users with any more updates than are really needed with an already-weekly release schedule.

Apologies about picking this change at random for this, but it's been something on my mind. 

It will show up in the next automatic release on Tuesday.

Thanks for understanding, and I really appreciate you keeping track of how ItemVersion is developing and in need of translation.

**Comment by Brainc3ll** [comment]
I understand, no worries ;)

**Pull request merged**
