### PR TITLE
Create frFR.lua

### PR DESCRIPTION
**Pull request by Brainc3ll**
French translation

## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Item fix
- [ ] Documentation
- [ ] Other

## Checklist

- [x] I've tested what I've added
- [ ] I've updated AUTHORS.md with my name (if I want to)

## Description

Please describe your changes here. If this fixes a bug, please link to the issue, if possible.

### CODE REVIEW

**Comment by Brainc3ll** [comment]
Hello, this is my first time with github, if i made mistake, i'm sorry ;)

**Comment by t-mart** [comment]
> Hello, this is my first time with github, if i made mistake, i'm sorry ;)

Hey, sweet! Thanks.

Looks good so far.

I'll review this more closely as soon as I can (today or tomorrow). If everything's okay, I'll cut a new release for you.

No pressure at all, but do you want to add your name to [AUTHORS.md](https://github.com/t-mart/ItemVersion/blob/master/AUTHORS.md?plain=1)? This is just a way to give people recognition for their efforts.

**Comment by t-mart** [comment]
Ah, ok, you made two pull requests: this one and #72. Both are related to the same feature (your translation).

Could you add another commit to this pull request with the change from #72? Then, we can close it and just work on this one. That would be ideal because we only have to think about this feature in _one_ place, instead of _two_.

PRs can involve _any_ number of files. It's even common to repeatedly change the same file multiple times in the same PR as development continues.

You said you're new: Do you want to try to figure out how to do that on your own, or would you like some pointers?

**Comment by Brainc3ll** [comment]
Hello, thank you for your message, I think I've figured out how to do it ;)

My name is not needed in Authors.md thank you for proposing it

**Comment by t-mart** [comment]
Looks good to me.

https://github.com/t-mart/ItemVersion/assets/200012/52fa60dd-4052-4b01-9f66-8db120457c31

If you want to see what it will look like, get the file [here named `ItemVersion-4a04a1cbaceee87b4affba7b3255d77ca31e2a6c `](https://github.com/t-mart/ItemVersion/actions/runs/8188660489) and put it in your AddOns directory.

I'm going to work on one more thing, and then I'll make a release.

**Comment by t-mart** [comment]
Release here: https://www.curseforge.com/wow/addons/itemversion/files/5165246

Thanks again!

**Pull request merged**
