### PR TITLE
Move Chat Output to Tooltip

### PR DESCRIPTION
**Pull request by BStramke**
Removes the MouseOver Error Spam and instead displays it inside of the Tooltip.
Also added 2 Items to Item Database.

### CODE REVIEW

**Comment by t-mart** [comment]
Hey there. Thanks for the PR. I have not been playing the game for some time, so there are a lot of things to update and design choices needing fix, such as the spam, as many people have commented.

Few questions and requests:

- Why add those files to the gitignore? Those seem like files we do want to track.
- How did you find the 9.2.5 item ids? I'm just looking for an idea if the additions are complete.

  Side note: Up until 2022-04-26, that data file was getting programmatically updated by another piece of code that I wrote, so that it didn't need manual updates. It would find all the new item ids and spit out the `Data.lua` file. This was nice because it could scan through all versions of WoW, not just one. But eventually, something about the API I was using changed and the code broke.

  Since then, I imagine many additional versions of the game have been released, right? For completeness, do we need to look back at versions before 9.2.5, the version that you added items for?

- Thanks for taking a stab at the error spam. Putting the error into the tooltip is a better approach.
  
  I'd like to see a little more on it, though:
  - We should change the string `Not Found by Addon` to `Not in ItemVersion` (or something similar that identifies the addon). Then, a user can more easily figure decide if they want to, say, file a bug report here, disable the addon, etc.
  - In these not-found cases, I think we should mute the color of the tooltip text so that it is less prominent and indicates something exceptional/error-y. `80CA3C3C`, for example, lowers the opacity from the current color from 100% to 50% (I think).

**Comment by BStramke** [comment]
- I didn't know it would also track other changes than the initial commit, so you can ignore the .gitignore file. Basically i added that to ignore the Files that are directly in the wow /addons/ItemVersion/ folder
- The Data.lua IDs came from WowHead and I am aware that they might not have the proper BuildVersion (it is a 9.2.5 Build, but there might be more than one). To get the ItemIds i used their Items Search with a "Added in patch = 9.2.5" Filter. Above the Header next to the Page selector is a button where you can copy all IDs. URL: [https://www.wowhead.com/items/group-by:level?filter=82;3;90205](url)
- PS: I changed the Tooltip Format as requested

**Comment by t-mart** [comment]
Alright, understood. 

Last thing:

- Please remove the the gitignore additions and the TOC.

  I think you may have added these files because you wanted to be able to place this repository directly in the addons directory during development. Therefore, you had to copy the Lua files up into the root and copy the TOC (from the zip file of a released version of the addon?), right?

  I actually created a [development tool](https://github.com/t-mart/wap) that installs the development addon for you into your Addons folder and generates the TOC file. I intended it to be used here with ItemVersion. But, that was a long time ago, and I'm not sure I want to maintain that project. 

  For now, can you please remove the TOC and gitignore additions from your commit? You can keep them in your local copy of the repository, just don't commit the changes. In another commit, I think I will update the project structure so that you do not need to jump through those hoops (lua files in root directory and TOC included).

Otherwise, things are looking good:
- The 9.2.5 items are good (for now).  I'm going to spend some time today to fix my code that retrieves the latest items (with proper build number), but for now, we can move forward with your changes to that file.
- I like your changes to the tooltip. We'll move forward with those.
- Give me some time to test your changes. I'm reinstalling the game right now to make sure everything looks ok.

**Comment by BStramke** [comment]
Changed as requested, i hope everything else is progressing fine ;)

**Comment by t-mart** [comment]
I just decided to run the project checks on you commits (a typical step before merging). For one thing, it lints the Lua code to make sure there aren't any statically-recognizable bugs.

As you can see from the check details, it found some in your edits to the data file.

> ...
> ItemVersion/Data.lua:4:1430163: value assigned to field '191200' is overwritten on line 4 before use
> ...

This is saying that the field (key) `191200` has been defined twice in this table -- it's redundant for there to multiple because only the last one will have an effect. (E.g. `tbl = {a=1, a=2}; print(tostring(tbl.a == 2));`)

Just while we're resurrecting this project, I'm going to forego this check and commit it anyway.

Additionally, I completed work on fixing the item importer. Will working on incorporating when I can.

**Pull request merged**
